---
title: "<i>invivoPKfit</i> and <i>CvTdb</i> figures"
author: "Christopher Cook"
date: "1/31/2022"
output:
  html_document: default
  word_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(results = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(data.table)
library(readxl)
devtools::load_all(".")
```

```{r, run_invivoPKfit, eval = FALSE}

#################
#################

data <- read.csv("inst/ext/cvt_query_for_john_27may2021_v2.csv")
data <- read.csv("inst/ext/cvtdb_invivopkfit_02242022.csv")

#################
#################

### fix compound names
data$analyte_name_original[data$analyte_name_original == "Methyleugonal "] <- "Methyleugonal"
data$analyte_name_original[data$analyte_name_original == "benzo[a]pyrene"] <- "benzo(a)pyrene"
data$analyte_name_original[data$analyte_name_original == "2,4-D"] <- "2,4-Dichlorophenoxyacetic acid"
data$analyte_name_original[data$analyte_name_original == "Diclofenac"] <- "Hexobarbital"
data$analyte_name_original[data$analyte_name_original == "Pentadecafluorooctanoic acid"] <- "Perfluorooctanoic acid"

### make fk_reference_document equal fk_extraction document if fk_reference_document is NULL
data$fk_reference_document_id[data$fk_reference_document_id == "NULL"] <- data$fk_extraction_document_id[data$fk_reference_document_id == "NULL"]

### do 1-Compartment fit
system.time(PK.fit.table.1comp <- fit_all(
  
  data.set = data,
  model = "1compartment",
  modelfun = "analytic",
  compound.col = "analyte_name_original",
  cas.col = "dsstox_casrn",
  reference.col = "fk_reference_document_id",
  species.col = "species",
  species.weight.col = "weight_kg",
  species.weight.units.default = "kg",
  dose.col = "dose_level_normalized",
  time.col = "time_hr",
  time.units.default = "hr",
  media.col = "conc_medium_normalized",
  media.units.default = "normalized",
  value.col = "conc",
  units.default = NA,
  route.col = "administration_route_normalized",
  source.col = "document_id",
  loq.default = NA,
  subject.default = NA,
  info.default = NA,
  ratio.data.to.dose = 0.001
))

### do 2-Compartment fit
system.time(PK.fit.table.2comp <- fit_all(
  
  data.set = data,
  model = "2compartment",
  modelfun = "analytic",
  compound.col = "analyte_name_original",
  cas.col = "dsstox_casrn",
  reference.col = "fk_reference_document_id",
  species.col = "species",
  species.weight.col = "weight_kg",
  species.weight.units.default = "kg",
  dose.col = "dose_level_normalized",
  time.col = "time_hr",
  time.units.default = "hr",
  media.col = "conc_medium_normalized",
  media.units.default = "normalized",
  value.col = "conc",
  units.default = NA,
  route.col = "administration_route_normalized",
  source.col = "fk_extraction_document_id",
  loq.default = NA,
  subject.default = NA,
  info.default = NA,
  ratio.data.to.dose = 0.001
))

# write.csv(PK.fit.table.1comp[[1]], "inst/ext/PK.fit.table.1comp.DATE.csv", row.names = FALSE)
# write.csv(PK.fit.table.1comp[[2]], "inst/ext/processed.1comp.data.DATE.csv", row.names = FALSE)
# 
# write.csv(PK.fit.table.2comp[[1]], "inst/ext/PK.fit.table.2comp.02102022.csv", row.names = FALSE)
# write.csv(PK.fit.table.2comp[[2]], "inst/ext/processed.2comp.data.02102022.csv", row.names = FALSE)
```

```{r, read_data}

### read in PK output files
pk_output_1comp_12212021 <- read.csv("inst/ext/PK.fit.table.1comp.12212021.csv")
pk_output_2comp_02102022 <- read.csv("inst/ext/PK.fit.table.2comp.02102022.csv")
pk_output_flat_02102022 <- read.csv("inst/ext/PK.fit.table.flat.02102022.csv")

pk_output_1comp_03012022 <- read.csv("inst/ext/PK.fit.table.1comp.03012022.csv")
pk_output_2comp_03012022<- read.csv("inst/ext/PK.fit.table.2comp.03012022.csv")
pk_output_flat_03012022 <- read.csv("inst/ext/PK.fit.table.flat.03012022.csv")

### read in processed raw data files
raw_1comp_12212021 <- read.csv("inst/ext/processed.1comp.data.12212021.csv")
raw_2comp_02102022 <- read.csv("inst/ext/processed.2comp.data.02102022.csv")
raw_flat_02102022 <- read.csv("inst/ext/processed.flat.data.02102022.csv")

raw_1comp_03012022 <- read.csv("inst/ext/processed.1comp.data.03012022.csv")
raw_2comp_03012022 <- read.csv("inst/ext/processed.2comp.data.03012022.csv")
raw_flat_03012022 <- read.csv("inst/ext/processed.flat.data.03012022.csv")

pk_lombardo <- read_xlsx("inst/ext/Supplemental_82966_revised_corrected.xlsx")
```

```{r, make_rdata, eval = FALSE}

### save data
# save(pk_output_1comp_12212021, file = "figures_rdata/pk_output_1comp_12212021.Rdata")
# save(pk_output_2comp_02102022, file = "figures_rdata/pk_output_2comp_12212021.Rdata")
# save(pk_output_flat_02102022, file = "figures_rdata/pk_output_flat_02102022.Rdata")
# save(raw_1comp_12212021, file = "figures_rdata/raw_1comp_12212021.Rdata")
# save(raw_2comp_02102022, file = "figures_rdata/raw_2comp_12212021.Rdata")
# save(raw_flat_02102022, file = "figures_rdata/raw_flat_02102022.Rdata")

save(pk_output_1comp_03012022, file = "figures_rdata/pk_output_1comp_03012022.Rdata")
save(pk_output_2comp_03012022, file = "figures_rdata/pk_output_2comp_03012022.Rdata")
save(pk_output_flat_03012022, file = "figures_rdata/pk_output_flat_03012022.Rdata")
save(raw_1comp_03012022, file = "figures_rdata/raw_1comp_03012022.Rdata")
save(raw_2comp_03012022, file = "figures_rdata/raw_2comp_03012022.Rdata")
save(raw_flat_03012022, file = "figures_rdata/raw_flat_03012022.Rdata")

save(pk_lombardo, file = "figures_rdata/pk_lombardo_02072022.Rdata")

### save cp data
# save(cp_df, file = "figures_rdata/cp_df.Rdata")
```

```{r, load_data}

### load all of this wonderful data
load("figures_rdata/pk_output_1comp_12212021.Rdata")
load("figures_rdata/pk_output_2comp_12212021.Rdata")
load("figures_rdata/raw_1comp_12212021.Rdata")
load("figures_rdata/raw_2comp_12212021.Rdata")
load("figures_rdata/cp_df_12212021.Rdata")
load("figures_rdata/cvt_variability_df_12212021.Rdata")

load("figures_rdata/pk_output_1comp_03012022.Rdata")
load("figures_rdata/pk_output_2comp_03012022.Rdata")
load("figures_rdata/pk_output_flat_03012022.Rdata")
load("figures_rdata/raw_1comp_03012022.Rdata")
load("figures_rdata/raw_2comp_03012022.Rdata")
load("figures_rdata/raw_flat_03012022.Rdata")
load("figures_rdata/cp_df_03012022.Rdata")
load("figures_rdata/cvt_variability_df_03012022.Rdata")

load("figures_rdata/cp_df_03302022.Rdata")

load("figures_rdata/pk_lombardo_02072022.Rdata")
```

```{r, make_invivoPKfit_plots, eval = FALSE}

### 1 compartment

pk_output_1comp_03012022 <- pk_output_1comp_03012022 %>%
  filter(Compound == "tamoxifen") %>%
  filter(Data.Analyzed != "Joint Analysis")

raw_1comp_03012022 <- raw_1comp_03012022 %>%
  filter(Compound == "tamoxifen")

junk <- plot_conctime(PK.fit.table = as.data.table(pk_output_1comp_12212021),
                      data.set = as.data.table(raw_1comp_12212021),
                      model = "1compartment")

### 2 compartment
junk <- plot_conctime(PK.fit.table = as.data.table(pk_output_2comp_03012022),
                      data.set = as.data.table(raw_2comp_03012022),
                      model = "2compartment")

```

```{r, make_cp_rdata, eval = FALSE}
################################
### histogram showing data spread of invivoPKfit cp values
################################

###########
### this is 1-compartment data
###########

###################
###################

### subset to only actual model outputs and discard "Joint Analysis" rows
pk_data1 <- pk_output_1comp_03012022 %>%
  filter(param.value.type == "Fitted geometric mean" & Data.Analyzed != "Joint Analysis")

raw_data1 <- dplyr::select(raw_1comp_03012022, -c("kelim", 
                                                  "Vdist", 
                                                  "Fgutabs", 
                                                  "kgutabs"))

###################
###################

raw_data1$Reference <- as.character(raw_data1$Reference)

full_data_1 <- left_join(raw_data1, pk_data1, by = c("Compound", "CAS", "Reference"))
full_data_1 <- full_data_1 %>% filter(AIC != Inf)



### function that finds cp
find_cp_1 <- function(full_data_1) {plyr::adply(full_data_1, 1, mutate, cp = cp_1comp(time = Time,
                                                                                      params = full_data_1[1,],
                                                                                      dose = Dose,
                                                                                      iv.dose = iv))}



### have to split data frame into ones with unique parameter values because cp_1comp takes constants
split_df_1 <- split(full_data_1, list(full_data_1$Compound,
                                      full_data_1$Reference,
                                      full_data_1$CAS),
                    drop = TRUE)

cp_df_1 <- lapply(split_df_1, find_cp_1)

cp_df_1 <- do.call(rbind, cp_df_1)

### nomralize cp by Value
cp_df_1$cp_norm <- cp_df_1$cp / cp_df_1$Value
cp_df_1$type <- "1-Compartment"

###########
### this is 2-compartment data
###########

#######################
#######################

### subset to only actual model outputs and discard "Joint Analysis" rows
pk_data2 <- pk_output_2comp_03012022 %>%
  filter(param.value.type == "Fitted geometric mean" & Data.Analyzed != "Joint Analysis")

raw_data2 <- dplyr::select(raw_2comp_03012022, -c("kelim", 
                                                  "Vdist", 
                                                  "Fgutabs", 
                                                  "kgutabs",
                                                  "V1",
                                                  "Ralphatokelim",
                                                  "Fbetaofalpha"))

########################
########################

raw_data2$Reference <- as.character(raw_data2$Reference)

full_data_2 <- left_join(raw_data2, pk_data2, by = c("Compound", "CAS", "Reference"))
full_data_2 <- full_data_2 %>% filter(AIC != Inf)
split_df_2 <- split(full_data_2, list(full_data_2$Compound,
                                      full_data_2$Reference,
                                      full_data_2$CAS),
                    drop = TRUE)

### function that finds cp
find_cp_2 <- function(full_data_2) {plyr::adply(full_data_2, 1, mutate, cp = cp_2comp(time = Time,
                                                                                      params = full_data_2[1,],
                                                                                      dose = Dose,
                                                                                      iv.dose = iv))}
cp_df_2 <- lapply(split_df_2, find_cp_2)

cp_df_2 <- do.call(rbind, cp_df_2)

cp_df_2$cp_norm <- cp_df_2$cp / cp_df_2$Value
cp_df_2$type <- "2-Compartment"

# cp_df_2 <- cp_df_2 %>%
#   filter(cp != 1e-20)

###########
### this is flat data
###########

pk_data_flat <- pk_output_flat_03012022 %>%
  filter(param.value.type == "Fitted geometric mean" & Data.Analyzed != "Joint Analysis")

raw_data_flat <- dplyr::select(raw_flat_03012022, -c("A"))

raw_data_flat$Reference <- as.character(raw_data_flat$Reference)

full_data_flat <- left_join(raw_data_flat, pk_data_flat, by = c("Compound", "CAS", "Reference"))
full_data_flat <- full_data_flat %>% filter(AIC != Inf)
split_df_flat <- split(full_data_flat, list(full_data_flat$Compound,
                                            full_data_flat$Reference,
                                            full_data_flat$CAS),
                       drop = TRUE)

### function that finds cp
find_cp_flat <- function(full_data_flat) {plyr::adply(full_data_flat, 1, mutate, cp = cp_flat(time = Time,
                                                                                              params = full_data_flat[1,],
                                                                                              dose = Dose,
                                                                                              iv.dose = iv))}
cp_df_flat <- lapply(split_df_flat, find_cp_flat)

cp_df_flat <- do.call(rbind, cp_df_flat)

cp_df_flat$cp_norm <- cp_df_flat$cp / cp_df_flat$Value
cp_df_flat$type <- "Flat"

#######################
#######################

### make all data.frames have the same column names so they are rbind-able
cp_df_1 <- cp_df_1[, intersect(colnames(cp_df_2), colnames(cp_df_1))]
cp_df_2 <- cp_df_2[, intersect(colnames(cp_df_1), colnames(cp_df_2))]

cp_df <- rbind(cp_df_1, cp_df_2)

cp_df <- cp_df[, intersect(colnames(cp_df_flat), colnames(cp_df))]
cp_df_flat <- cp_df_flat[, intersect(colnames(cp_df), colnames(cp_df))]

cp_df <- rbind(cp_df, cp_df_flat)

cp_df$cp_pred_error <- (cp_df$cp - cp_df$Value) / cp_df$Value

cp_df <- cp_df %>% group_by(Species.x, 
                            Compound,
                            CAS,
                            type) %>%
  mutate(cp_pred_error_range = max(cp_pred_error, na.rm = TRUE) - min(cp_pred_error, na.rm = TRUE))

cp_df_03302022 <- cp_df

save(cp_df_03302022, file = "figures_rdata/cp_df_03302022.Rdata")
```


```{r, make_cp_histogram}

##################
##################

# data <- cp_df_12212021
data <- cp_df_03012022

##################
##################

p <- ggplot(data = data,
            mapping = aes(x = cp_norm)) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept = c(0.5, 2),
             color = "Red",
             linetype = "dashed") +
  # xlim(0, 1e42) +
  # ylim(0, 400) +
  # scale_y_log10()+
  theme(title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14)) +
  scale_x_log10(limits = c(0.01, 1000)) +
  theme_bw() +
  labs(x = "Predicted/Observed",
       y = "Number of Observations") +
  facet_wrap(. ~ type)

p
```

```{r, make_cp_error_histogram}

##################
##################

# data <- cp_df_12212021
data <- cp_df_03012022

##################
##################

data <- data %>%
  filter(cp != 1e-20)

data <- data %>%
  distinct(Species.x, Compound, CAS, cp_pred_error_range)

p <- ggplot(data = data,
            mapping = aes(x = cp_pred_error_range)) +
  geom_histogram() +
  scale_x_log10() +
  facet_wrap(. ~type)

p
```

```{r, make_cp_error_versus_dose}

##################
##################

data <- cp_df_03012022

##################
##################

data <- data %>%
  filter(type == "1-Compartment")

data <- data %>%
  group_by(Compound, CAS, Dose) %>%
  mutate(average = mean(cp_pred_error))

p <- ggplot(data = data, mapping = aes(x = Dose, y = average)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

p

```

```{r, make_cvt_variability_rdata, eval = FALSE}

##################
##################

data <- as.data.table(raw_1comp_03012022)

##################
##################

### function that finds mean conc of each replicate timepoint
find_mean_conc <- function(data) {
  
  ### only use data with replicate timepoints
  data <- data[ ave(1:nrow(data), data$Time, FUN = length) > 1 , ]
  
  if(nrow(data) == 0) {
    return(NULL)
  } else {
    
    time_split <- split(data, data$Time)
    
    ### discard replicate timepoints where all concentrations are NA
    time_split_list <- purrr::discard(time_split, ~all(is.na(.$Value)))
    
    if(length(time_split_list) == 0) {
      return(NULL)
    } else {
      
      data <- do.call(rbind, time_split_list)
      
      ### where some replicate concentration data are NA, set them equal to the LOQ
      data$Value[is.na(data$Value)] <- data$LOQ[is.na(data$Value)]
      
      ### take the average Value for each set of timepoints
      data <- data %>%
        group_by(Time) %>%
        do(mutate(., mean_conc = mean(.$Value, na.rm = TRUE)))
      
      data <- data %>%
        group_by(Time) %>%
        do(mutate(., range_conc = max(.$Value) - min(.$Value)))
      
      ### create normalized conc values by dividing conc by mean_conc
      data$conc_norm <- data$Value/data$mean_conc
      
      data <- data[order(data$Time), ]
      
      return(data)
    }
  }
}

data.list <- list()
for(this.compound in unique(data[, Compound])) {
  this.compound.data <- data[Compound == this.compound]
  
  ### list of columns by which to split data.set
  col_list <- list(this.compound.data$Reference,
                   this.compound.data$Dose,
                   this.compound.data$Route,
                   this.compound.data$Media)
  
  ### split data.set into list of data.tables
  split_list <- split(this.compound.data, col_list)
  
  ### remove data.tables with 0 rows
  split_list <- keep(split_list, ~nrow(.) > 0)
  
  ### use find_mean_conc fn
  mean_conc <- lapply(split_list, find_mean_conc)
  
  test <- do.call(rbind, mean_conc)
  
  data.list[[this.compound]] <- test
}

### combine data.tables back into one large data.set
cvt_variability_df_03012022 <- do.call(rbind, data.list)

save(cvt_variability_df_03012022, file = "figures_rdata/cvt_variability_df_03012022.Rdata")
```

```{r, make_cvt_variability_histogram}

#################
#################

data <- cvt_variability_df_03012022
# data <- cvt_variability_df_12212021

#################
#################

p <- ggplot(data, aes(x = conc_norm)) +
  geom_histogram(binwidth = 0.25) +
  xlim(c(-0.5, 4)) +
  geom_vline(xintercept = c(0.5, 2),
             color = "Red",
             linetype = "dashed") +
  theme_bw() +
  labs(x = "Normalized concentration",
       y = "Number of observations")
p
```

```{r, make_density_plot}

##################
##################

# pk_data <- cp_df_03012022
pk_data <- cp_df_03302022

cvt_data <- cvt_variability_df_03012022

##################
##################

row.names(pk_data) <- c()

cvt_data <- dplyr::select(cvt_data, -c("kelim", 
                                       "Vdist", 
                                       "Fgutabs", 
                                       "kgutabs"))

### split pk_data by model so you can properly join with raw data
model_split <- split(pk_data, pk_data$model)

cvt_data$Reference <- as.character(cvt_data$Reference)

cvt_data$type <- "1-Compartment"
full_data_1 <- left_join(cvt_data, model_split$`1compartment`)

cvt_data$type <- "2-Compartment"
full_data_2 <- left_join(cvt_data, model_split$`2compartment`)

cvt_data$type <- "Flat"
full_data_flat <- left_join(cvt_data, model_split$`flat`)

### put data back together
full_data <- rbind(full_data_1, full_data_2, full_data_flat)

full_data <- full_data %>%
  filter(cp != 0)

full_data$AIC <- round(full_data$AIC, digits = 4)

full_data <- full_data %>%
  distinct(Compound, Reference, model, conc_norm, AIC, cp_norm)

### 
full_data <- full_data %>%
  pivot_wider(names_from = model,
              values_from = c(AIC, cp_norm)) %>%
  unchop(everything()) 

full_data <- full_data %>% mutate(model = case_when(AIC_1compartment < AIC_2compartment & 
                                                      AIC_1compartment < AIC_flat ~ "1compartment",
                                                    AIC_2compartment < AIC_1compartment &
                                                      AIC_2compartment < AIC_flat ~ "2compartment",
                                                    AIC_flat < AIC_1compartment &
                                                      AIC_flat < AIC_2compartment ~ "flat",
                                                    
                                                    !is.na(AIC_1compartment) & is.na(AIC_2compartment) &
                                                      is.na(AIC_flat) ~ "1compartment",
                                                    !is.na(AIC_2compartment) & is.na(AIC_1compartment) & 
                                                      is.na(AIC_flat) ~ "2compartment",
                                                    !is.na(AIC_flat) & is.na(AIC_1compartment) & 
                                                      is.na(AIC_2compartment) ~ "flat",
                                                    
                                                    is.na(AIC_1compartment) &
                                                      AIC_flat < AIC_2compartment ~ "flat",
                                                    is.na(AIC_1compartment) &
                                                      AIC_2compartment < AIC_flat ~ "2compartment",
                                                    is.na(AIC_2compartment) &
                                                      AIC_flat < AIC_1compartment ~ "flat",
                                                    is.na(AIC_2compartment) &
                                                      AIC_1compartment < AIC_flat ~ "1compartment",
                                                    is.na(AIC_flat) &
                                                      AIC_1compartment < AIC_2compartment ~"1compartment",
                                                    is.na(AIC_flat) &
                                                      AIC_2compartment <AIC_1compartment ~"2compartment"))

full_data <- full_data %>%
  mutate(cp_norm = case_when(model == "1compartment" ~ cp_norm_1compartment,
                             model == "2compartment" ~ cp_norm_2compartment,
                             model == "flat" ~ cp_norm_flat))

# full_data <- full_data %>%
#   mutate(cp_norm = case_when(model == "1comparment" ~ cp_norm_1compartment,
#                              model == "2compartment" ~ cp_norm_2compartment))

# full_data$cp_norm[full_data$model == "2compartment"] <- full_data$cp_norm_2compartment
# full_data$cp_norm[full_data$model == "1compartment"] <- full_data$cp_norm_1compartment

# full_data <- full_data %>%
# mutate(across(everything(), ~ifelse(. == "", NA, as.character(.))))

# filter(Compound != "triclosan")
# filter(Compound != "tamoxifen")

###########
###########
###########

split_full_data <- split(full_data, full_data$model)

full_data_1 <- split_full_data$`1compartment`

### Find number of points in each plot panel for 1-compartment
full_data_1_center <- full_data_1 %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_1_center <- full_data_1_center %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_1_center <- nrow(full_data_1_center) / nrow(full_data_1 %>% filter(!is.na(cp_norm)))

full_data_1_green <- full_data_1 %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_1_green <- full_data_1_green %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_1_green <- nrow(full_data_1_green) / nrow(full_data_1 %>% filter(!is.na(cp_norm)))

full_data_1_gray <- full_data_1 %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_1_gray <- full_data_1_gray %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_1_gray <- nrow(full_data_1_gray) / nrow(full_data_1 %>% filter(!is.na(cp_norm)))

full_data_1_tan <- full_data_1 %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_1_tan <- full_data_1_tan %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_1_tan <- nrow(full_data_1_tan) / nrow(full_data_1 %>% filter(!is.na(cp_norm)))

###########
###########

full_data_2 <- split_full_data$`2compartment`

### Find number of points in each plot panel for 2-compartment
full_data_2_center <- full_data_2 %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_2_center <- full_data_2_center %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_2_center <- nrow(full_data_2_center) / nrow(full_data_2 %>% filter(!is.na(cp_norm)))

full_data_2_green <- full_data_2 %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_2_green <- full_data_2_green %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_2_green <- nrow(full_data_2_green) / nrow(full_data_2 %>% filter(!is.na(cp_norm)))

full_data_2_gray <- full_data_2 %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_2_gray <- full_data_2_gray %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_2_gray <- nrow(full_data_2_gray) / nrow(full_data_2 %>% filter(!is.na(cp_norm)))

full_data_2_tan <- full_data_2 %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_2_tan <- full_data_2_tan %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_2_tan <- nrow(full_data_2_tan) / nrow(full_data_2 %>% filter(!is.na(cp_norm)))

###########
###########

full_data_flat <- split_full_data$`flat`

### Find number of points in each plot panel for 2-compartment
full_data_flat_center <- full_data_flat %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_flat_center <- full_data_flat_center %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_flat_center <- nrow(full_data_flat_center) / nrow(full_data_flat %>% filter(!is.na(cp_norm)))

full_data_flat_green <- full_data_flat %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_flat_green <- full_data_flat_green %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_flat_green <- nrow(full_data_flat_green) / nrow(full_data_flat %>% filter(!is.na(cp_norm)))

full_data_flat_gray <- full_data_flat %>% filter(conc_norm < 0.5 | conc_norm > 2)
full_data_flat_gray <- full_data_flat_gray %>% filter(cp_norm >= 0.5 & cp_norm <= 2)
ratio_flat_gray <- nrow(full_data_flat_gray) / nrow(full_data_flat %>% filter(!is.na(cp_norm)))

full_data_flat_tan <- full_data_flat %>% filter(conc_norm >= 0.5 & conc_norm <= 2)
full_data_flat_tan <- full_data_flat_tan %>% filter(cp_norm < 0.5 | cp_norm > 2)
ratio_flat_tan <- nrow(full_data_flat_tan) / nrow(full_data_flat %>% filter(!is.na(cp_norm)))

###########
###########
###########

# rect_df1 <- data.frame(xmin = c(0, 0, 2, 2, 0, 2, 0.5, 0.5),
#                       xmax = c(0.5, 0.5, Inf, Inf, 0.5, Inf, 2, 2),
#                       ymin = c(2, 0, 0, 2, 0.5, 0.5, 2, 0),
#                       ymax = c(Inf, 0.5, 0.5, Inf, 2, 2, Inf, 0.5),
#                       panel_key = c(paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_green, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_green, digits = 1), "%", ")", sep = ""),
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_green, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_green, digits = 1), "%", ")", sep = ""),
#                                           sep = " "),
#                                     paste("Good Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_tan, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Good Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_1_tan, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                    paste("Poor Fit, Typical Data", 
#                                           paste("(", round(100 * ratio_1_gray, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                    paste("Poor Fit, Typical Data", 
#                                           paste("(", round(100 * ratio_1_gray, digits = 1), "%", ")", sep = ""), 
#                                           sep = " ")))
# 
# rect_df2 <- data.frame(xmin = c(0, 0, 2, 2, 0, 2, 0.5, 0.5),
#                       xmax = c(0.5, 0.5, Inf, Inf, 0.5, Inf, 2, 2),
#                       ymin = c(2, 0, 0, 2, 0.5, 0.5, 2, 0),
#                       ymax = c(Inf, 0.5, 0.5, Inf, 2, 2, Inf, 0.5),
#                       panel_key = c(paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_green, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_green, digits = 1), "%", ")", sep = ""),
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_green, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Poor Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_green, digits = 1), "%", ")", sep = ""),
#                                           sep = " "),
#                                     paste("Good Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_tan, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                     paste("Good Fit, Outlier Data", 
#                                           paste("(", round(100 * ratio_2_tan, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                    paste("Poor Fit, Typical Data", 
#                                           paste("(", round(100 * ratio_2_gray, digits = 1), "%", ")", sep = ""), 
#                                           sep = " "),
#                                    paste("Poor Fit, Typical Data", 
#                                           paste("(", round(100 * ratio_2_gray, digits = 1), "%", ")", sep = ""), 
#                                           sep = " ")))
# 
# 
# rect_p1 <- ggplot() +
#   geom_rect(data = rect_df1, aes(xmin = xmin,
#                                 ymin = ymin,
#                                 xmax = xmax,
#                                 ymax = ymax,
#                                 fill = panel_key),
#             alpha = 0.3, inherit.aes = FALSE) +
#   scale_fill_manual(name = "Panel Key",
#                     values = c("#361D2E",
#                                "#86A397",
#                                "#E1B07E")) +
#   theme_bw() +
#   theme(panel.spacing = unit(2, "lines")) +
#   geom_vline(xintercept = c(0.5, 2),
#              linetype = "dashed") +
#   geom_hline(yintercept = c(0.5, 2),
#              linetype = "dashed") +
#   scale_x_log10() +
#   scale_y_log10() +
#   labs(x = "Data Variability",
#        y = "Model Error") +
#   guides(fill = guide_legend(override.aes = list(size = 0.1)))
# 
# rect_p2 <- ggplot() +
#   geom_rect(data = rect_df2, aes(xmin = xmin,
#                                 ymin = ymin,
#                                 xmax = xmax,
#                                 ymax = ymax,
#                                 fill = panel_key),
#             alpha = 0.3, inherit.aes = FALSE) +
#   scale_fill_manual(name = "Panel Key",
#                     values = c("#361D2E",
#                                "#86A397",
#                                "#E1B07E")) +
#   theme_bw() +
#   theme(panel.spacing = unit(2, "lines")) +
#   geom_vline(xintercept = c(0.5, 2),
#              linetype = "dashed") +
#   geom_hline(yintercept = c(0.5, 2),
#              linetype = "dashed") +
#   scale_x_log10() +
#   scale_y_log10() +
#   labs(x = "Data Variability",
#        y = "Model Error") +
#   guides(fill = guide_legend(override.aes = list(size = 0.1)))
# 
# ###################
# fill_legend1 <- get_legend(rect_p1)
# fill_legend2 <- get_legend(rect_p2)
# ##################

p <- ggplot(data = full_data,
            mapping = aes(x = conc_norm, y = cp_norm)) +
  annotate(geom = "rect", xmin = 0, xmax = 0.5, ymin = 2, ymax = Inf, alpha = 0.3, fill = "#86A397") +
  annotate(geom = "rect", xmin = 0, xmax = 0.5, ymin = 0, ymax = 0.5, alpha = 0.3, fill = "#86A397") +
  annotate(geom = "rect", xmin = 2, xmax = Inf, ymin = 0, ymax = 0.5, alpha = 0.3, fill = "#86A397") +
  annotate(geom = "rect", xmin = 2, xmax = Inf, ymin = 2, ymax = Inf, alpha = 0.3, fill = "#86A397") +
  annotate(geom = "rect", xmin = 0, xmax = 0.5, ymin = 0.5, ymax = 2, alpha = 0.3, fill = "#361D2E") +
  annotate(geom = "rect", xmin = 2, xmax = Inf, ymin = 0.5, ymax = 2, alpha = 0.3, fill = "#361D2E") +
  annotate(geom = "rect", xmin = 0.5, xmax = 2, ymin = 2, ymax = Inf, alpha = 0.3, fill = "#E1B07E") +
  annotate(geom = "rect", xmin = 0.5, xmax = 2, ymin = 0, ymax = 0.5, alpha = 0.3, fill = "#E1B07E") +
  annotate(geom = "rect", xmin = 0.5, xmax = 2, ymin = 0.5, ymax = 2.0, alpha = 0.5, fill = "black") +
  theme_bw() +
  theme(panel.spacing = unit(2, "lines")) +
  geom_bin2d(bins = 100) +
  scale_fill_distiller(palette = "Blues") +
  geom_vline(xintercept = c(0.5, 2),
             linetype = "dashed") +
  geom_hline(yintercept = c(0.5, 2),
             linetype = "dashed") +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Data Variability",
       y = "Model Performance") +
  facet_wrap(. ~ model)

p

# ##################
# 
# data_p_final <- data_p +
#   # inset_element(fill_legend1, 0.1, 1, 0.5, 1) +
#   inset_element(fill_legend2, 0.6, 0.5, 0.7, 0.2, clip = TRUE)
#  
# data_p_final
```

```{r, make_sigma_distribution_histogram}

##################
##################

data1 <- pk_output_1comp_03012022 %>%
  filter(param.value.type == "Fitted geometric mean" & AIC != Inf & Data.Analyzed != "Joint Analysis")

data2 <- pk_output_2comp_03012022 %>%
  filter(param.value.type == "Fitted geometric mean" & AIC != Inf & Data.Analyzed != "Joint Analysis")

##################
##################

### assign new column, with either "1-Compartment" or "2-Compartment"
data1 <- subset(data1, select = sigma_value)
data1$model <- "1-Compartment"

data2 <- subset(data2, select = sigma_value)
data2$model <- "2-Compartment"

data <- rbind(data1, data2)

p <- ggplot(data = data,
            mapping = aes(x = sigma_value)) +
  geom_histogram(bins = 15) +
  # geom_density() +
  # scale_y_log10()+
  scale_x_log10() +
  theme_bw() +
  labs(x = "Sigma",
       y = "Number of observations") +
  facet_wrap(.~ model)
  # geom_vline(xintercept = 0.001476315)
# stat_function(fun = dlnorm, args = list(mean = mean(log(data$sigma_value)), sd = sd(log(data$sigma_value))))

p
```

```{r make_magnitude_histogram}

##################
##################

data <- raw_1comp_03012022

##################
##################

data$X <- NULL

split_df <- split(data, list(data$Compound,
                             data$Reference,
                             data$CAS,
                             data$Dose,
                             data$Species,
                             data$Route,
                             data$Media),
                  drop = TRUE)

### find number of orders of magnitude
find_mag <- function(data) {
  
  data$Value <- abs(data$Value)
  
  diff <- log10(max(data$Value, na.rm = TRUE)) - log10(min(data$Value, na.rm = TRUE))
  
  diff <- round(diff)
  
  return(diff)
  
}

data <- lapply(split_df, find_mag)


data <- pivot_longer(as.data.frame(data), cols = everything())

p <- ggplot(data = data, mapping = aes(x = value)) +
  geom_histogram(bins = 5, binwidth = 0.5) +
  xlab("Orders of magnitude") + theme_bw()

p
```

```{r make_joint_sigma_plot, eval = FALSE}

##################
##################

data1 <- as.data.table(pk_output_1comp_03012022 %>%
                         filter(param.value.type == "Fitted geometric mean"))

data2 <- as.data.table(pk_output_2comp_03012022 %>%
                         filter(param.value.type == "Fitted geometric mean"))

##################
##################

### find data with repeated sigma_id values
find_rep_sigma <- function(data) {
  
  data <- data[ ave(1:nrow(data), data$sigma_id, FUN=length) > 1 , ]
  
  if(nrow(data) == 0) {
    return(NULL)
  } else {
    
    return(data)
  }
}

split_list_1 <- split(data1, data1$Compound)
rep_sigma_1 <- lapply(split_list_1, find_rep_sigma)
data1 <- do.call(rbind, rep_sigma_1)
data1 <- subset(data1, select = c(param.value.type, sigma_id, sigma_value, Data.Analyzed, Compound))
data1$Data.Analyzed[data1$Data.Analyzed != "Joint Analysis"] <- "Ind Analysis"
data1 <- data1 %>% pivot_wider(names_from = Data.Analyzed, values_from = sigma_value)
data1 <- data1 %>% filter(sigma_id != "sigma2.14")
data1$`Joint Analysis` <- as.numeric(data1$`Joint Analysis`)
data1$`Ind Analysis` <- as.numeric(data1$`Ind Analysis`)
data1$model <- "1-Compartment"

split_list_2 <- split(data2, data2$Compound)
rep_sigma_2 <- lapply(split_list_2, find_rep_sigma)
data2 <- do.call(rbind, rep_sigma_2)
data2 <- subset(data2, select = c(param.value.type, sigma_id, sigma_value, Data.Analyzed, Compound))
data2$Data.Analyzed[data2$Data.Analyzed != "Joint Analysis"] <- "Ind Analysis"
data2 <- data2 %>% pivot_wider(names_from = Data.Analyzed, values_from = sigma_value)
data2 <- data2 %>% filter(sigma_id != "sigma2.14")
data2$`Joint Analysis` <- as.numeric(data2$`Joint Analysis`)
data2$`Ind Analysis` <- as.numeric(data2$`Ind Analysis`)
data2$model <- "2-Compartment"

data <- rbind(data1, data2)

p <- ggplot(data, aes(x = `Ind Analysis`, y = `Joint Analysis`)) +
  geom_point() +
  scale_y_log10() +
  scale_x_log10() +
  geom_abline(slope = 1) +
  facet_wrap(. ~ model)
p
```

```{r, make_halflife_count_histogram}

###########
### one compartment
###########

##################
##################

raw_data1 <- raw_1comp_03012022

##################
##################

pk_data1 <- pk_output_1comp_03012022 %>% 
  filter(param.value.type == "Fitted geometric mean" & Data.Analyzed != "Joint Analysis")

pk_data1$X <- NULL


raw_data1$Reference <- as.character(raw_data1$Reference)

raw_data1 <- dplyr::select(raw_data1, -c("X",
                                         "kelim",
                                         "Vdist",
                                         "Fgutabs",
                                         "kgutabs"))

# pk_data2 <- pk_output_2comp_12212021

full_data_1 <- left_join(raw_data1, pk_data1, by = c("Compound", "CAS", "Reference"))

full_data_1 <- full_data_1 %>% filter(AIC != Inf)


find_halflife_count <- function(data) {
  
  data_subset <- data %>% filter(!is.na(Value))
  
  max_time <- max(unique(data_subset$Time))
  
  data$halflife_count <- max_time/data$halflife
  
  return(data)
  
}

split_full_data_1 <- split(full_data_1, list(full_data_1$Compound,
                                             full_data_1$Reference,
                                             full_data_1$CAS,
                                             full_data_1$Dose,
                                             full_data_1$Species.x,
                                             full_data_1$Route,
                                             full_data_1$Media),
                           drop = TRUE)

full_data_1_hl <- lapply(split_full_data_1, find_halflife_count)

full_data_1_hl <- do.call(rbind, full_data_1_hl)


full_data_1_hl <- full_data_1_hl %>%
  distinct(Compound,
           Reference,
           CAS,
           Dose,
           Species.x,
           Route,
           Media,
           halflife_count)

full_data_1_hl$model <- "1-Compartment"

###########
### two compartment
###########

##################
##################

raw_data2 <- raw_2comp_03012022

pk_data2 <- pk_output_2comp_03012022 %>% 
  filter(param.value.type == "Fitted geometric mean" & Data.Analyzed != "Joint Analysis")

##################
##################

pk_data2$X <- NULL


raw_data2$Reference <- as.character(raw_data2$Reference)

raw_data2 <- dplyr::select(raw_data2, -c("kelim", 
                                         "Vdist", 
                                         "Fgutabs", 
                                         "kgutabs",
                                         "V1",
                                         "Ralphatokelim",
                                         "Fbetaofalpha"))

# pk_data2 <- pk_output_2comp_12212021

full_data_2 <- left_join(raw_data2, pk_data2, by = c("Compound", "CAS", "Reference"))

full_data_2 <- full_data_2 %>% filter(AIC != Inf)


find_halflife_count <- function(data) {
  
  data_subset <- data %>% filter(!is.na(Value))
  
  max_time <- max(unique(data_subset$Time))
  
  data$halflife_count <- max_time/data$halflife
  
  return(data)
  
}

split_full_data_2 <- split(full_data_2, list(full_data_2$Compound,
                                             full_data_2$Reference,
                                             full_data_2$CAS,
                                             full_data_2$Dose,
                                             full_data_2$Species.x,
                                             full_data_2$Route,
                                             full_data_2$Media),
                           drop = TRUE)

full_data_2_hl <- lapply(split_full_data_2, find_halflife_count)

full_data_2_hl <- do.call(rbind, full_data_2_hl)


full_data_2_hl <- full_data_2_hl %>%
  distinct(Compound,
           Reference,
           CAS,
           Dose,
           Species.x,
           Route,
           Media,
           halflife_count)

full_data_2_hl$model <- "2-Compartment"

###########
###########
###########

full_data_hl <- rbind(full_data_1_hl, full_data_2_hl)

###########

p <- ggplot(data = full_data_hl, mapping = aes(x = halflife_count)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("halflife count") + 
  theme_bw() +
  # geom_vline(xintercept = 330.7598,
  #            color = "red",
  #            linetype = "dashed") + 
  facet_wrap(. ~ model)
p
```

```{r, make_max_loq_histogram}

###############
###############

raw_data1 <- raw_1comp_03012022

###############
###############

find_normalized_max <- function(data) {
  
  data$normalized_max <- max(data$Value, na.rm = TRUE)/data$LOQ
  
  return(data)
  
}

split_df_1 <- split(raw_data1, list(raw_data1$Compound,
                                    raw_data1$Reference,
                                    raw_data1$CAS,
                                    raw_data1$Dose,
                                    raw_data1$Species,
                                    raw_data1$Route,
                                    raw_data1$Media),
                    drop = TRUE)

raw_data1_normalized_max <- lapply(split_df_1, find_normalized_max)

raw_data1_normalized_max <- do.call(rbind, raw_data1_normalized_max)

raw_data1_normalized_max <- raw_data1_normalized_max %>%
  distinct(Compound,
           Reference,
           CAS,
           Dose,
           Species,
           Route,
           Media,
           normalized_max)

p <- ggplot(data = raw_data1_normalized_max, mapping = aes(x = normalized_max)) +
  geom_histogram(bins = 15) +
  scale_x_log10() +
  xlab("Max Concentration / LOQ") + 
  theme_bw()
# geom_vline(xintercept = 24.8482,
#            color = "red",
#            linetype = "dashed")
p
```

```{r, make_mean_loq_histogram}

###############
###############

raw_data1 <- raw_1comp_03012022

###############
###############

find_normalized_mean <- function(data) {
  
  data$normalized_mean <- mean(data$Value, na.rm = TRUE)/data$LOQ
  
  return(data)
  
}

split_df_1 <- split(raw_data1, list(raw_data1$Compound,
                                    raw_data1$Reference,
                                    raw_data1$CAS,
                                    raw_data1$Dose,
                                    raw_data1$Species,
                                    raw_data1$Route,
                                    raw_data1$Media),
                    drop = TRUE)

raw_data1_normalized_mean <- lapply(split_df_1, find_normalized_mean)

raw_data1_normalized_mean <- do.call(rbind, raw_data1_normalized_mean)

raw_data1_normalized_mean <- raw_data1_normalized_mean %>%
  distinct(Compound,
           Reference,
           CAS,
           Dose,
           Species,
           Route,
           Media,
           normalized_mean)

p <- ggplot(data = raw_data1_normalized_mean, mapping = aes(x = normalized_mean)) +
  geom_histogram(bins = 15) +
  scale_x_log10() +
  xlab("Mean Concentration / LOQ") + 
  theme_bw()
# geom_vline(xintercept = 24.8482,
#            color = "red",
#            linetype = "dashed")
p
```

```{r, make_model_params_table, eval = FALSE}

### this code almost entirely is imported from John's bake-off RMarkdown file
### what this produces is a table of compounds that were fit by at least one of the models
### AICs for both models are reported, and subsequent parameter values correspond to the model with the lower AIC

###################
###################

pk_data1 <- pk_output_1comp_03012022 
pk_data1 <- pk_output_1comp_12212021 

pk_data2 <- pk_output_2comp_03012022
pk_data2 <- pk_output_2comp_12212021 

###################
###################

pk_data1$sigma_id <- NULL
pk_data1$sigma_value <- NULL
pk_data2$sigma_id <- NULL
pk_data2$sigma_value <- NULL

pk_data1 <- distinct(pk_data1)
pk_data2 <- distinct(pk_data2)

fits1comp <- subset(pk_data1, is.finite(AIC) & AIC < 10^4)
fits2comp <- subset(pk_data2, is.finite(AIC) & AIC < 10^4)

#How many chemicals have 1 or 2 compartment fits:
length(unique(c(fits1comp$CAS,fits2comp$CAS)))

fittable <- NULL
for (this.cas in unique(c(fits1comp$CAS,fits2comp$CAS)))
{
  if (this.cas %in% fits1comp$CAS) this.compound <- fits1comp[
    fits1comp$CAS==this.cas,"Compound"][1]
  else this.compound <- fits2comp[
    fits2comp$CAS==this.cas,"Compound"][1]
  
  this.data.1comp <- subset(fits1comp,CAS==this.cas)
  this.data.2comp <- subset(fits2comp,CAS==this.cas)
  
  for (this.species in unique(tolower(c(
    this.data.1comp$Species,
    this.data.2comp$Species))))
  {
    Vdist.1comp <- NA
    kelim.1comp <- NA
    Vdist.2comp <- NA
    kelim.2comp <- NA
    
    this.data.1comp.species <- subset(this.data.1comp,tolower(Species)==this.species)
    this.data.2comp.species <- subset(this.data.2comp,tolower(Species)==this.species)
    
    this.row <- data.frame(
      Compound=this.compound,
      CAS=this.cas,
      Species=this.species,
      Reference=NA,
      AIC.1comp=NA,
      AIC.2comp=NA,
      Model=NA,
      Vdist=NA,
      kelim=NA)
    
    if (this.cas %in% fits1comp$CAS)
    {
      this.data.1comp.species <- subset(this.data.1comp.species,
                                        param.value.type=="Fitted geometric mean")
      
      # If more than one source, require that the joint analysis worked:
      if (dim(this.data.1comp.species)[1]>1)
      {
        this.data.1comp.species<- subset(this.data.1comp.species, 
                                         Data.Analyzed=="Joint Analysis")
      }
      if (dim(this.data.1comp.species)[1]>0) 
      {
        this.row$AIC.1comp <- this.data.1comp.species$AIC
        Vdist.1comp <- this.data.1comp.species$Vdist
        kelim.1comp <- this.data.1comp.species$kelim
        this.row$Reference <- this.data.1comp.species$Reference
      }
    }
    
    if (this.cas %in% fits2comp$CAS)
    {
      this.data.2comp.species <- subset(this.data.2comp.species,
                                        param.value.type=="Fitted geometric mean")
      
      # If more than one source, require that the joint analysis worked:
      if (dim(this.data.2comp.species)[1]>1)
      {
        this.data.2comp.species <- subset(this.data.2comp.species, 
                                          Data.Analyzed=="Joint Analysis")
      }
      if (dim(this.data.2comp.species)[1]>0) 
      {
        this.row$AIC.2comp <- this.data.2comp.species$AIC
        Vdist.2comp <- this.data.2comp.species$Vss
        kelim.2comp <- this.data.2comp.species$kelim
        this.row$Reference <- this.data.2comp.species$Reference
      }
    }
    
    if (!is.na(this.row$AIC.1comp))
    {
      if (!is.na(this.row$AIC.2comp))
      {
        if (this.row$AIC.1comp < this.row$AIC.2comp)
        {
          this.row$Model <- "1Comp"
        } else this.row$Model <- "2Comp"
      } else this.row$Model <- "1Comp"
    } else if (!is.na(this.row$AIC.2comp))
    {
      this.row$Model <- "2Comp"
    }
    
    if (!is.na(this.row$Model))
      if (this.row$Model == "1Comp")
      {
        this.row$Vdist <- Vdist.1comp
        this.row$kelim <- kelim.1comp
      } else 
      {
        this.row$Vdist <- Vdist.2comp
        this.row$kelim <- kelim.2comp
      }      
    
    fittable <- rbind(fittable,this.row)
  }
}
fittable$halflife <- log(2)/fittable$kelim

#Lets only keep chemicals where we can fit a PK model:
fittable <- subset(fittable, !is.na(Model))

for (this.col in c("AIC.1comp","AIC.2comp","Vdist","kelim","halflife"))
  fittable[,this.col] <- signif(as.numeric(fittable[,this.col]),4)

# We have parameters estimated for 86 chemicals:
dim(fittable)[1]

write.csv(fittable, file = "inst/ext/model_params_table_03012022.csv", row.names = FALSE)

```

```{r, make_no_fit_table}

##################
##################

pk_data1 <- as.data.table(pk_output_1comp_03012022)
pk_data2 <- as.data.table(pk_output_2comp_03012022)

##################
##################

pk_data1 <- pk_data1 %>%
  filter(param.value.type == "Fitted geometric mean") %>%
  dplyr::select(c("Compound", "CAS", "Reference", "AIC")) %>%
  mutate(model = "1-Compartment")

pk_data2 <- pk_data2 %>%
  filter(param.value.type == "Fitted geometric mean") %>%
  dplyr::select(c("Compound", "CAS", "Reference", "AIC")) %>%
  mutate(model = "2-Compartment")

pk_all <- rbind(pk_data1, pk_data2)

### loop that says if a compound has any references that do not have AIC of Inf, it was a fit compound
this.compound.list <- list()
for (this.compound in unique(pk_all[, Compound])) {
  
  this.compound.data <- pk_all[Compound == this.compound]
  
  if(any(this.compound.data$AIC != Inf)) {
    this.compound.data$status <- "good fit"
  } else {
    this.compound.data$status <- "bad fit"
  }
  
  this.compound.list[[this.compound]] <- this.compound.data
  
}

pk_all <- do.call(rbind, this.compound.list)

pk_all <- pk_all %>%
  filter(status == "bad fit") %>% ### only want bad fit
  mutate(status = NULL) %>% ### get rid of status column
  group_by(Compound) %>%  
  filter(n() == 2) %>% ### group_by compound and only keep compounds with two observations, aka neither model worked
  mutate(model = NULL) %>% ### get rid of model column
  distinct() ### discard repeated compound names

# write.csv(pk_all, file = "inst/ext/no_fit_table_03012022.csv", row.names = FALSE)
```

```{r, compare_AIC}

##################
##################

pk_data1 <- pk_output_1comp_03012022

pk_data2 <- pk_output_2comp_03012022

pk_data_flat <- pk_output_flat_03012022 %>%
  filter(param.value.type == "Predicted" | param.value.type == "Fitted geometric mean" | param.value.type == "Fitted geometric std dev")

##################
##################

### make both data.frames have the same column names so they are rbind-able
pk_data1 <- pk_data1[, intersect(intersect(colnames(pk_data2), colnames(pk_data_flat)), colnames(pk_data1))]
pk_data2 <- pk_data2[, intersect(intersect(colnames(pk_data1), colnames(pk_data_flat)), colnames(pk_data2))]
pk_data_flat <- pk_data_flat[, intersect(intersect(colnames(pk_data1), colnames(pk_data2)), colnames(pk_data_flat))]

pk_data1 <- pk_data1 %>%
  rename(LogLikelihood_1 = LogLikelihood,
         AIC_1 = AIC,
         sigma_value_1 = sigma_value) %>%
  mutate(model = NULL) %>%
  mutate(model.type = NULL)

pk_data2 <- pk_data2 %>%
  rename(LogLikelihood_2 = LogLikelihood,
         AIC_2 = AIC,
         sigma_value_2 = sigma_value) %>%
  mutate(model = NULL) %>%
  mutate(model.type = NULL)

pk_data_flat <- pk_data_flat %>%
  rename(LogLikelihood_flat = LogLikelihood,
         AIC_flat = AIC,
         sigma_value_flat = sigma_value) %>%
  mutate(model = NULL) %>%
  mutate(model.type = NULL)

pk_all <- left_join(pk_data1, pk_data2, by = c("CAS",
                                               "Species",
                                               "param.value.type",
                                               "sigma_id",
                                               "Reference",
                                               "Data.Analyzed",
                                               "Compound"))

pk_all <- left_join(pk_all, pk_data_flat, by = c("CAS",
                                                 "Species",
                                                 "param.value.type",
                                                 "sigma_id",
                                                 "Reference",
                                                 "Data.Analyzed",
                                                 "Compound"))

pk_all <- subset(pk_all, select = c(CAS, Species, Compound, Reference, AIC_1, AIC_2, AIC_flat))

pk_all <- distinct(pk_all)

pk_all$AIC_1[pk_all$AIC_1 == Inf] <- NA
pk_all$AIC_2[pk_all$AIC_2 == Inf] <- NA
pk_all$AIC_flat[pk_all$AIC_flat == Inf] <- NA

pk_all <- pk_all %>%
  mutate(flat_lowest = ifelse(AIC_flat < AIC_1 & AIC_flat < AIC_2, 1, 0)) %>%
  mutate(flat_better_than_1 = ifelse(AIC_flat < AIC_1 & AIC_flat > AIC_2, 1, 0)) %>%
  mutate(flat_better_than_2 = ifelse(AIC_flat > AIC_1 & AIC_flat < AIC_2, 1, 0))

pk_just_bad <- pk_all %>%
  filter(flat_lowest == 1 | flat_better_than_1 == 1 | flat_better_than_2)
```

```{r, lombardo_comparisons}

##################
##################

pk_data1 <- pk_output_1comp_03012022

pk_lombardo <- pk_lombardo

##################
##################

pk_data1 <- pk_data1 %>%
  filter(param.value.type == "Fitted geometric mean", Species == "human")

pk_all <- left_join(pk_data1, pk_lombardo, by = c("CAS" = "CAS #"))

pk_all <- pk_all %>%
  filter(!is.na(`human VDss (L/kg)`), 
         !is.na(`human CL (mL/min/kg)`))

### volume of distribution comparison
p1 <- ggplot(pk_all, aes(x = Vdist, y = `human VDss (L/kg)`)) +
  geom_point() +
  scale_x_log10() +
  geom_abline(slope = 1, intercept = 0)

p1

### half-life comparision
p2 <- ggplot(pk_all, aes(x = halflife, y = `terminal  t1/2 (h)`)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0)

p2

### clearance comparison

### convert to same units
pk_all$`human CL (L/hr/kg)` <- pk_all$`human CL (mL/min/kg)` * 60 / 1000

p3 <- ggplot(data = pk_all, mapping = aes(x = CLtot, y = `human CL (L/hr/kg)`)) +
  geom_point() +
  scale_x_log10() +
  geom_abline(slope = 1, intercept = 0)

p3


```





