---
title: "Clearance Project - 3 - TKstats"
author: "Gilberto Padilla Mercado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library-loading}
today <- format(Sys.Date(), "%d%b%Y")
devtools::load_all()
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ctxR)
library(patchwork)
```

```{r data-loading}
this_pk <- readRDS("data-raw/plasma_CvTfits.rds")
load("data-raw/chem_lists.RData")
load("data-raw/plasma_CvTfits_data.RData")
load("data-raw/rat_pars_human.RData")
all_chem_properties <- readRDS("data-raw/ctxR_3comp2_cheminfo.rds")
```

```{r combination-function}
combo_gen_splitter <- function(df, N = 3L, split_col) {
  # Checks
  stopifnot(
    is.character(split_col),
    is.data.frame(df),
    is.integer(N)
  )
  
  # arrange by split_col and make ID column (row number)
  df <- arrange(df, split_col)
  df$ID <- 1:NROW(df)
  
  # Split the data.frames (both combo sets)
  df_split <- split(df, df[[split_col]])
  # full_combos <- expand.grid(
  #   lapply(df_split,
  #          \(x) {
  #            tmp_combos <- combn(x[['ID']], N)
  #            apply(tmp_combos, MARGIN = 2, paste, collapse = ".")
  #          })
  # ) |> apply(1, paste, collapse = ".")
  
  internal_combos <- lapply(df_split,
           \(x) {
             tmp_combos <- combn(x[['ID']], N)
             apply(tmp_combos, MARGIN = 2, paste, collapse = ".")
           })
  
  # Check to see if full sampling will cause vector length issues
  # Max length = 2^30 so we will set it to something comfortably below this
  max_length = 14
  prob_vectors <- sum(log2(vapply(internal_combos, length, numeric(1L)))
  )
  
  if (prob_vectors > max_length) {
    message("Full sampling too memory intensive, performing random sampling")
    
    for (i in rev(seq(0.001, 0.6, by = 0.001))) {
      npv <- sum(log2(floor(i * vapply(internal_combos, length, numeric(1L)))))
      
      if (npv < max_length) {
        print(paste("Proportion that works: ", i))
        print(paste("Number of full combinations expected: ", 2^npv))
        
        internal_combos <- lapply(
          internal_combos, \(x) {
            prop_len = floor(length(x) * i)
            sample(x, size = prop_len)
          }
        )
        break
      }
    }
  }
  
  full_combos <- expand.grid(internal_combos)
  
  full_combos <- apply(full_combos,1, paste, collapse = ".")
  
  # Generate list of numeric for row filtering
  split_combos <- strsplit(full_combos, split = "\\.")
  
  # Generate list of sampled data sets
  full_df_combos <- lapply(split_combos,
         \(x) {
           df[x,]
         })
  
  message(paste("Unique dataset samples: ", length(full_df_combos)))
  
  invisible(full_df_combos)
}


```

```{r example_chemical}
# Using the example chemical
full_pk <- readRDS("data-raw/all_cvt_pk.rds")
full_tkstats <- get_tkstats(full_pk)


get_data(full_pk) %>% filter(Conc > pLOQ) %>% count(Chemical, Species, Reference, Route, Dose, Time) %>% arrange(-n) %>%
  mutate(combos = choose(n,3)) %>%
  group_by(Chemical, Species, Reference, Route, Dose) %>%
  summarize(TotalnCr = sum(combos)) %>% arrange(-TotalnCr) %>% 
  right_join(full_pk$fit) %>% View()

test_chem <- "DTXSID6073499"
full_tkstats %>% filter(Chemical == test_chem) %>% glimpse()


test_chem_data <- get_data(full_pk) %>%
  filter(Chemical == test_chem)

test_chem_data %>%
  ggplot(aes(Time, Conc)) +
  geom_point() +
  facet_wrap(~Route+Dose+Media) +
  theme_bw()

test_chem_data_listsplits <- combo_gen_splitter(
  test_chem_data,
  4L,
  'Time'
)

# Takes way too long, parallelize it

clust <- parallel::makeCluster(parallel::detectCores()-2L)
parallel::clusterCall(clust, function() devtools::load_all())
system.time(
  Css_list <- parallel::parLapply(clust, test_chem_data_listsplits,
                                  \(x) {
                                    tmp_pk <- pk(x,
                                                 mapping = ggplot2::aes(
                                                   Chemical = Chemical,
                                                   Chemical_Name = Chemical_Name,
                                                   DTXSID = DTXSID,
                                                   CASRN = CASRN,
                                                   Species = Species,
                                                   Reference = Reference,
                                                   Media = Media,
                                                   Route = Route,
                                                   Dose = Dose,
                                                   Dose.Units = "mg/kg",
                                                   Subject_ID = Subject_ID,
                                                   Series_ID = Series_ID,
                                                   Study_ID = Study_ID,
                                                   ConcTime_ID = ConcTime_ID,
                                                   N_Subjects = N_Subjects,
                                                   Weight = Weight,
                                                   Weight.Units = "kg",
                                                   Time = Time,
                                                   Time.Units = "hours",
                                                   Value = Value,
                                                   Value.Units = "mg/L",
                                                   Value_SD = Value_SD,
                                                   LOQ = LOQ
                                                 )
                                    ) +
                                      scale_conc(dose_norm = TRUE,
                                                 log10_trans = TRUE) +
                                      settings_optimx(method = c(
                                        "bobyqa"
                                      ))
                                    
                                    tmp_pk <- do_fit(tmp_pk)
                                    tmp_tkstats <- get_tkstats(tmp_pk) %>%
                                      distinct(Chemical, Species, Reference,
                                               Route, Media,
                                               model, method,
                                               Css, CLtot, halflife)
                                    
                                    return(tmp_tkstats)
                                  })
)
parallel::stopCluster(clust)

Css_df_full <- bind_rows(Css_list)

```


```{r}
num_samples <- length(Css_list)

test_chem_full_tkstats <- full_tkstats %>%
  filter(Chemical == test_chem, model != "model_flat") %>%
  distinct(Chemical, Species, model, Css)

css_hist <- Css_df_full %>%
  filter(model != "model_flat") %>%
  ggplot(aes(x = Css)) +
  geom_histogram(fill = "grey5", binwidth = 0.2) +
  geom_vline(data = test_chem_full_tkstats,
             aes(xintercept = Css),
             color = "green4",
             linetype = "dashed") +
  facet_grid(rows = vars(model)) +
  labs(title = unique(test_chem_data$Chemical_Name),
       subtitle = paste("Number of samples: ", num_samples)) +
  scale_x_log10() +
  xlim(0,50) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 1),
        plot.subtitle = element_text(hjust = 1))

css_lines <- Css_df_full %>%
  filter(model != "model_flat") %>%
  group_by(model) %>%
  mutate(grouping = row_number()) %>%
  ggplot(aes(x = model, y = Css)) +
  geom_point(alpha = 0.4) +
  geom_line(aes(group=grouping), alpha = 0.02) +
  scale_y_log10() +
  labs(subtitle = "N per timepoint: 4") +
  theme_bw()

get_winning_model(full_pk) %>% filter(Chemical == test_chem) %>% glimpse()

css_hist + css_lines

ggsave(filename = paste0(Sys.getenv("FIG_DIR"),
                         "RestrictiveClearance_Analysis/",
                         "CURRENT_", test_chem,
                         "_Css_pseudobootstrapping.png"),
       bg = "white",
       height = 3, width = 5
)
```



