devtools::load_all()

#' 1-compartment model object.
model_1comp <- pk_model(name = "model_1comp",
                    params = c("kelim", "Vdist", "Fgutabs",
                               "kgutabs", "Fgutabs_Vdist", "Rblood2plasma"),
                    conc_fun = "cp_1comp",
                    auc_fun = "auc_1comp",
                    params_fun = "get_params_1comp",
                    tkstats_fun = "tkstats_1comp",
                    conc_fun_args = NULL,
                    auc_fun_args = NULL,
                    params_fun_args = NULL,
                    tkstats_fun_args = NULL)


model_2comp <- pk_model(name = "model_2comp",
                    params = c("kelim", "k12", "k21", "V1", "Fgutabs",
                               "kgutabs", "Fgutabs_V1", "Rblood2plasma"),
                    conc_fun = "cp_2comp",
                    auc_fun = "auc_2comp",
                    params_fun = "get_params_2comp",
                    tkstats_fun = "tkstats_2comp",
                    conc_fun_args = NULL,
                    auc_fun_args = NULL,
                    params_fun_args = NULL,
                    tkstats_fun_args = NULL)

model_flat <- pk_model(name = "model_flat",
                    params = c("Vdist", "Fgutabs",
                               "Fgutabs_Vdist", "Rblood2plasma"),
                    conc_fun = "cp_flat",
                    auc_fun = "auc_flat",
                    params_fun = "get_params_flat",
                   tkstats_fun = "tkstats_flat",
                    conc_fun_args = NULL,
                    auc_fun_args = NULL,
                    params_fun_args = NULL,
                   tkstats_fun_args = NULL)

model_1comp_cl_rest <- pk_model(name = "model_1comp_cl_rest",
                             params = c("Clint",
                                        "Q_gfr",
                                        "Q_totli",
                                        "Q_alv",
                                        "Kblood2air",
                                        "Fup",
                                        "Vdist", "Fgutabs", "kgutabs",
                                        "Fgutabs_Vdist", "Rblood2plasma"),
                             conc_fun = "cp_1comp_cl",
                             auc_fun = "auc_1comp_cl",
                             params_fun = "get_params_1comp_cl",
                             tkstats_fun = "tkstats_1comp_cl",
                             conc_fun_args = list(restrictive = TRUE),
                             auc_fun_args = NULL,
                             params_fun_args = list(restrictive = TRUE),
                             tkstats_fun_args = NULL)

model_1comp_cl_nonrest <- pk_model(name = "model_1comp_cl_nonrest",
                                params = c("Clint",
                                           "Q_gfr",
                                           "Q_totli",
                                           "Q_alv",
                                           "Kblood2air",
                                           "Fup",
                                           "Vdist", "Fgutabs", "kgutabs",
                                           "Fgutabs_Vdist", "Rblood2plasma"),
                                conc_fun = "cp_1comp_cl",
                                auc_fun = "auc_1comp_cl",
                                params_fun = "get_params_1comp_cl",
                                tkstats_fun = "tkstats_1comp_cl",
                                conc_fun_args = list(restrictive = FALSE),
                                auc_fun_args = NULL,
                                params_fun_args = list(restrictive = FALSE),
                                tkstats_fun_args = NULL)

model_1comp_fup <- pk_model(name = "model_1comp_fup",
                             params = c("Clint",
                                        "Q_gfr",
                                        "Q_totli",
                                        "Q_alv",
                                        "Kblood2air",
                                        "Fup",
                                        "Vdist", "Fgutabs", "kgutabs",
                                        "Fgutabs_Vdist", "Rblood2plasma"),
                             conc_fun = "cp_1comp_cl",
                             auc_fun = "auc_1comp_cl",
                             params_fun = "get_params_1comp_fup",
                             tkstats_fun = "tkstats_1comp_cl",
                             conc_fun_args = list(restrictive = TRUE),
                             auc_fun_args = NULL,
                             params_fun_args = NULL,
                             tkstats_fun_args = NULL)

model_1comp_rad <- pk_model(name = "model_1comp_rad",
                             params = c("Clint",
                                        "Q_gfr",
                                        "Q_totli",
                                        "Q_alv",
                                        "Kblood2air",
                                        "Fup",
                                        "Vdist", "Fgutabs", "kgutabs",
                                        "Fgutabs_Vdist", "Rblood2plasma",
                                        "Frec"),
                             conc_fun = "cp_1comp_rad",
                             auc_fun = "auc_1comp_rad",
                             params_fun = "get_params_1comp_rad",
                             tkstats_fun = "tkstats_1comp_rad",
                             conc_fun_args = NULL,
                             auc_fun_args = NULL,
                             params_fun_args = list(restrictive = TRUE),
                             tkstats_fun_args = NULL)

model_httk_3comp2 <- pk_model(name = "model_httk_3comp2",
                              params = c("BW",
                                         "Caco2.Pab",
                                         "Caco2.Pab.dist",
                                         "Clint",
                                         "Clint.dist",
                                         "Clmetabolismc",
                                         "Funbound.plasma",
                                         "Funbound.plasma.dist",
                                         "Funbound.plasma.adjustment",
                                         "Fabsgut",
                                         "Fhep.assay.correction",
                                         "hematocrit",
                                         "Kgut2pu",
                                         "Krbc2pu",
                                         "kgutabs",
                                         "Kliver2pu",
                                         "Krest2pu",
                                         "Kblood2air",
                                         "liver.density",
                                         "logHenry",
                                         "million.cells.per.gliver",
                                         "MW",
                                         "Pow",
                                         # pKa values are added in get_params
                                         "MA",
                                         "Qcardiacc",
                                         "Qgfrc",
                                         "Qgutf",
                                         "Qliverf",
                                         "Qalvc",
                                         "Rblood2plasma",
                                         "Vgutc",
                                         "Vliverc",
                                         "Vrestc"
                              ),
                              conc_fun = "cp_httk_3comp2",
                              auc_fun = "auc_httk_3comp2",
                              params_fun = "get_params_httk_3comp2",
                              tkstats_fun = "tkstats_httk_3comp2",
                              conc_fun_args = list(restrictive = TRUE,
                                                   this_chem = quote(Chemical),
                                                   this_species = quote(Species)),
                              auc_fun_args = NULL,
                              params_fun_args = list(restrictive = TRUE,
                                                     this_chem = quote(Chemical),
                                                     this_species = quote(Species)),
                              tkstats_fun_args = NULL)


usethis::use_data(model_1comp,
                  model_1comp_cl_rest,
                  model_1comp_cl_nonrest,
                  model_1comp_fup,
                  model_httk_3comp2,
                  model_1comp_rad,
                  model_2comp,
                  model_flat,
                  internal = FALSE,
                  overwrite = TRUE)

