---
title: "invivoPKfit analysis of CvTdb data"
author: "Christopher Cook, John Wambaugh, Caroline Ring"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: default
  word_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(results = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(data.table)
library(readxl)
devtools::load_all("../invivopkfit")
```

Read in CvTdb data pulled in `pulling_oral_iv_data_cvtdb.Rmd`.

```{r, load_cvt, eval = TRUE}
cvt_data <- fread("../inst/ext/cvt_data_2022_12_15_16_20_21.csv")
```

Run a one-compartment fit on the data, and write out the results. Timestamp the file name with the current date and time (at the beginning of the runs) in format YYYY_MM_DD_hh_mm.

```{r}
timestamp <- format(Sys.time(), "%Y_%m_%d_%H_%M")
```

Fit the flat model.

```{r, run_invivoPKfit_flat}

system.time(
    PK.fit.table.flat <- fit_all(
     data.set = cvt_data,
      model = "flat",
      modelfun = "analytic",
      names_list =list(
                      "Compound_Dosed" = "studies.test_substance_name_original",
                      "DTXSID_Dosed" = "chemicals_dosed.dsstox_substance_id",
                      "CAS_Dosed" = "chemicals_dosed.dsstox_casrn",
                      "Compound_Analyzed" = "series.analyte_name_original",
                      "DTXSID_Analyzed" = "chemicals_analyzed.dsstox_substance_id",
                      "CAS_Analyzed" = "chemicals_analyzed.dsstox_casrn",
                      "Reference" = "documents_reference.id",
                      "Extraction" = "documents_extraction.id",
                      "Species" = "subjects.species",
                      "Weight" ="subjects.weight_kg",
                      "Weight.Units" = NULL,
                      "Dose" = "studies.dose_level_normalized",
                      "Dose.Units" = NULL,
                      "Time" = "conc_time_values.time_hr",
                      "Time.Units" = NULL,
                      "Media" = "series.conc_medium_normalized",
                      "Value" = "conc_time_values.conc",
                      "Value.Units" = NULL,
                      "Route" = "studies.administration_route_normalized",
                      "LOQ" = "series.loq",
                      "Subject" = "subjects.id",
                      "N_Subjects" = "series.n_subjects_in_series",
                      "Value_SD" = "conc_time_values.conc_sd"),
                    defaults_list =   list(
                      "Weight.Units" = "kg",
                      "Dose.Units" = "mg/kg",
                      "Time.Units" = "h",
                      "Value.Units" = "mg/L"),
      ratio_conc_to_dose = 1,
                    calc_loq_factor = 0.45,
                    routes_keep = c("po", "iv"),
                    media_keep = c("blood", "plasma"),
      optimx_args = list(
                      "method" = "bobyqa",
                      "itnmax" = 1e6,
                      "control" = list("kkt" = FALSE)
                    ),
      suppress.messages = TRUE
    )
)

write.csv(PK.fit.table.flat, paste("inst/ext/PK_fit_table_flat_",
                                    timestamp,
                                    ".csv",
                                    sep=""), row.names = FALSE)

rm(PK.fit.table.flat)
```


Fit the 1-compartment model.

```{r, run_invivoPKfit_1comp}

### do 1-Compartment fit
system.time(
    PK.fit.table.1comp <- fit_all(
      data.set = cvt_data,
      model = "1compartment",
      modelfun = "analytic",
      names_list =list(
                      "Compound_Dosed" = "studies.test_substance_name_original",
                      "DTXSID_Dosed" = "chemicals_dosed.dsstox_substance_id",
                      "CAS_Dosed" = "chemicals_dosed.dsstox_casrn",
                      "Compound_Analyzed" = "series.analyte_name_original",
                      "DTXSID_Analyzed" = "chemicals_analyzed.dsstox_substance_id",
                      "CAS_Analyzed" = "chemicals_analyzed.dsstox_casrn",
                      "Reference" = "documents_reference.id",
                      "Extraction" = "documents_extraction.id",
                      "Species" = "subjects.species",
                      "Weight" ="subjects.weight_kg",
                      "Weight.Units" = NULL,
                      "Dose" = "studies.dose_level_normalized",
                      "Dose.Units" = NULL,
                      "Time" = "conc_time_values.time_hr",
                      "Time.Units" = NULL,
                      "Media" = "series.conc_medium_normalized",
                      "Value" = "conc_time_values.conc",
                      "Value.Units" = NULL,
                      "Route" = "studies.administration_route_normalized",
                      "LOQ" = "series.loq",
                      "Subject" = "subjects.id",
                      "N_Subjects" = "series.n_subjects_in_series",
                      "Value_SD" = "conc_time_values.conc_sd"),
                    defaults_list =   list(
                      "Weight.Units" = "kg",
                      "Dose.Units" = "mg/kg",
                      "Time.Units" = "h",
                      "Value.Units" = "mg/L"),
      ratio_conc_to_dose = 1,
                    calc_loq_factor = 0.45,
                    routes_keep = c("po", "iv"),
                    media_keep = c("blood", "plasma"),
      optimx_args = list(
                      "method" = "bobyqa",
                      "itnmax" = 1e6,
                      "control" = list("kkt" = FALSE)
                    ),
      suppress.messages = TRUE
  )
)


write.csv(PK.fit.table.1comp,
          paste("../inst/ext/PK_fit_table_1comp_",
                                    timestamp,
                                    ".csv",
                                    sep=""),
          row.names = FALSE)

post_1comp <- postprocess_data(PK_fit = PK.fit.table.1comp,
                               model = "1compartment")

write.csv(post_1comp,
          paste("../inst/ext/PK_fit_postprocess_1comp_",
                                    timestamp,
                                    ".csv",
                                    sep=""),
          row.names = FALSE)

rm(PK.fit.table.1comp, post_1comp)

```

Fit the 2-compartment model.

```{r, run_invivoPKfit_2comp}
### do 2-Compartment fit
system.time(
    PK.fit.table.2comp <- fit_all(
      data.set = cvt_data,
      model = "2compartment",
      modelfun = "analytic",
      names_list =list(
                      "Compound_Dosed" = "studies.test_substance_name_original",
                      "DTXSID_Dosed" = "chemicals_dosed.dsstox_substance_id",
                      "CAS_Dosed" = "chemicals_dosed.dsstox_casrn",
                      "Compound_Analyzed" = "series.analyte_name_original",
                      "DTXSID_Analyzed" = "chemicals_analyzed.dsstox_substance_id",
                      "CAS_Analyzed" = "chemicals_analyzed.dsstox_casrn",
                      "Reference" = "documents_reference.id",
                      "Extraction" = "documents_extraction.id",
                      "Species" = "subjects.species",
                      "Weight" ="subjects.weight_kg",
                      "Weight.Units" = NULL,
                      "Dose" = "studies.dose_level_normalized",
                      "Dose.Units" = NULL,
                      "Time" = "conc_time_values.time_hr",
                      "Time.Units" = NULL,
                      "Media" = "series.conc_medium_normalized",
                      "Value" = "conc_time_values.conc",
                      "Value.Units" = NULL,
                      "Route" = "studies.administration_route_normalized",
                      "LOQ" = "series.loq",
                      "Subject" = "subjects.id",
                      "N_Subjects" = "series.n_subjects_in_series",
                      "Value_SD" = "conc_time_values.conc_sd"),
                    defaults_list =   list(
                      "Weight.Units" = "kg",
                      "Dose.Units" = "mg/kg",
                      "Time.Units" = "h",
                      "Value.Units" = "mg/L"),
      ratio_conc_to_dose = 1,
                    calc_loq_factor = 0.45,
                    routes_keep = c("po", "iv"),
                    media_keep = c("blood", "plasma"),
      optimx_args = list(
                      "method" = "bobyqa",
                      "itnmax" = 1e6,
                      "control" = list("kkt" = FALSE)
                    ),
      suppress.messages = TRUE
    )
)

write.csv(PK.fit.table.2comp, paste("../inst/ext/PK_fit_table_2comp_",
                                    timestamp,
                                    ".csv",
                                    sep=""), row.names = FALSE)

post_2comp <- postprocess_data(PK_fit = PK.fit.table.2comp,
                               model = "2compartment")

write.csv(post_2comp,
          paste("../inst/ext/PK_fit_postprocess_2comp_",
                                    timestamp,
                                    ".csv",
                                    sep=""),
          row.names = FALSE)

rm(PK.fit.table.2comp, post_2comp)
```
